Traceback (most recent call last):
  File "/home/nskane/ERGO/ERGO/ERGO.py", line 437, in <module>
    main(args)
  File "/home/nskane/ERGO/ERGO/ERGO.py", line 141, in main
    model, best_auc, best_roc = lstm.train_model(train_batches, test_batches, args.device, arg, params)
  File "/home/nskane/ERGO/ERGO/lstm_utils.py", line 176, in train_model
    loss = train_epoch(batches, model, loss_function, optimizer, device)
  File "/home/nskane/ERGO/ERGO/lstm_utils.py", line 140, in train_epoch
    loss = loss_function(probs, batch_signs)
  File "/home/nskane/.conda/envs/torch_env_run_4/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/nskane/.conda/envs/torch_env_run_4/lib/python3.9/site-packages/torch/nn/modules/loss.py", line 603, in forward
    return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)
  File "/home/nskane/.conda/envs/torch_env_run_4/lib/python3.9/site-packages/torch/nn/functional.py", line 2906, in binary_cross_entropy
    raise ValueError(
ValueError: Using a target size (torch.Size([50])) that is different to the input size (torch.Size([50, 1])) is deprecated. Please ensure they have the same size.
